### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by mgwg** [mgwg/light-pink-theme#1]
- [ ] Adjust Git colours
- [x] Pastel pink dark theme
- [ ] Change terminal highlight colour

**Comment by a2937** [comment]
I want to see this too. ❤️  

Anyway I believe this will help. [Git decoration value reference](https://code.visualstudio.com/api/references/theme-color#git-colors) 

I'm not quite sure what you meant by terminal highlight color but the entire page has a list of decoration values.

**Comment by Nanonej** [comment]
Hey @mgwg!

I just discovered this amazing light theme and I would love to contribute on this if you want so.
And also make a matching light theme for [Oh My Zsh](https://github.com/ohmyzsh/ohmyzsh/), as the only close one I found is [bubblegum-zsh](https://github.com/oddhorse/bubblegum-zsh).

Do you had a color palette for this or something like that ?

**Comment by mgwg** [comment]
Hey  @Nanonej :) 

I don't have a color palette for this, but you're welcome to adapt or contribute!

**Comment by a2937** [comment]
Omg this theme would be great.
